services:
  postgres:
    image: postgres:latest
    container_name: timescale-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: timescale_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: TimescaleApi.API/Dockerfile
    container_name: timescale-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=timescale_db;Username=user;Password=pass1234"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:8080"
      - "5001:8081"
    restart: on-failure


volumes:
  pgdata:
